# Name of workflow
name: Node CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    # The type of machine to run the job on
    runs-on: windows-2019
    strategy:
      # Node versions list
      matrix:
        node-version: [17.x]
    steps:
      # Check-out repository under GitHub workspace
      - name: Check out repository ${{ matrix.node-version }}
        uses: actions/checkout@v3
      # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        uses: actions/setup-node@v3
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm install --force

      - name: build prodaction project
        if: always()
        run: npm run build:prod

      - name: linting typescript
        if: always()
        run: npm run lint:ts

      - name: linting scss modules
        if: always()
        run: npm run lint:scss

      - name: unit testing
        if: always()
        run: npm run test:unit

      - name: build storybook
        if: always()
        run: npm run storybook:build

      - name: screenshot testing
        if: always()
        run: npm run test:ui:ci
